# Generated by Django 2.0.1 on 2018-09-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
