# Generated by Django 2.0.1 on 2018-09-01 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org', to=settings.AUTH_USER_MODEL),
        ),
    ]
