# Generated by Django 2.0.1 on 2018-09-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='file',
            field=models.FileField(upload_to='cu_events_images'),
        ),
    ]
