# Generated by Django 2.0.1 on 2018-09-01 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_main', '0002_auto_20180901_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event_media',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_media', to='backend_main.Event'),
        ),
    ]
