# Generated by Django 2.0.1 on 2018-09-01 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_main', '0002_auto_20180901_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorg',
            name='highlighted',
        ),
        migrations.RemoveField(
            model_name='org',
            name='highlighted',
        ),
    ]
