# Generated by Django 2.1.7 on 2019-08-28 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("backend_main", "0002_verifiedemails")]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        )
    ]
