# Generated by Django 2.0.1 on 2018-07-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_main', '0002_historicaltrial_trial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
