# Generated by Django 2.1.7 on 2019-09-01 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("backend_main", "0003_auto_20190827_2142")]

    operations = [
        migrations.CreateModel(
            name="Org_Media",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                )
            ],
        ),
        migrations.RemoveField(model_name="historicalorg", name="photo"),
        migrations.RemoveField(model_name="org", name="photo"),
        migrations.AlterField(
            model_name="media",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="org_media",
            name="media_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="backend_main.Media"
            ),
        ),
        migrations.AddField(
            model_name="org_media",
            name="org_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="backend_main.Org"
            ),
        ),
        migrations.AddField(
            model_name="org",
            name="media",
            field=models.ManyToManyField(
                through="backend_main.Org_Media", to="backend_main.Media"
            ),
        ),
    ]
