# Generated by Django 2.0.1 on 2018-09-08 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_main', '0003_auto_20180901_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='num_attendees',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='num_attendees',
            field=models.IntegerField(default=0),
        ),
    ]
