# Generated by Django 2.0.1 on 2018-10-25 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_main', '0003_auto_20180922_1724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='room',
        ),
    ]
