# Generated by Django 2.0.1 on 2018-07-18 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend_main', '0003_auto_20180718_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(default='Cornell University', on_delete=django.db.models.deletion.SET_DEFAULT, to='backend_main.Location'),
        ),
        migrations.AddField(
            model_name='historicalevent',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='backend_main.Location'),
        ),
    ]
