# Generated by Django 2.1.7 on 2019-09-01 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("backend_main", "0004_auto_20190901_1509")]

    operations = [
        migrations.RenameField(model_name="org", old_name="media", new_name="photo")
    ]
