# Generated by Django 2.1.7 on 2019-09-14 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_main', '0008_auto_20190912_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalorg',
            name='email',
        ),
        migrations.RemoveField(
            model_name='org',
            name='email',
        ),
    ]
