# Generated by Django 2.1.7 on 2019-09-14 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_main', '0009_auto_20190914_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorg',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='org',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
