# Generated by Django 2.1.7 on 2019-09-21 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_org',
            old_name='event_id',
            new_name='event',
        ),
        migrations.RenameField(
            model_name='event_org',
            old_name='org_id',
            new_name='org',
        ),
    ]
