# Generated by Django 2.2.10 on 2020-11-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historicalevent',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='historicalorg',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='historicalorg',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='building',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='place_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='room',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='media',
            name='link',
            field=models.TextField(default='https://dti-events-public.s3.amazonaws.com/default.jpg'),
        ),
        migrations.AlterField(
            model_name='org',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='org',
            name='name',
            field=models.TextField(),
        ),
    ]
