# Generated by Django 2.1.7 on 2019-09-01 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("backend_main", "0005_auto_20190901_1523")]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="backend_main.Org"
            ),
        )
    ]
