# Generated by Django 2.1.7 on 2019-09-01 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("backend_main", "0006_auto_20190901_1554")]

    operations = [
        migrations.RenameField(
            model_name="org_media", old_name="media_id", new_name="media"
        ),
        migrations.RenameField(
            model_name="org_media", old_name="org_id", new_name="org"
        ),
    ]
