# Generated by Django 2.1.7 on 2019-09-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_main', '0007_auto_20190901_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorg',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='org',
            name='email',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
